### ISSUE TITLE
DefaultAccount for wallet struct does not function as expected

### ISSUE THREAD

**Issue by csajedi** [Zilliqa/gozilliqa-sdk#5] opened 2019-10-15 16:21 UTC
I'm using this sdk to translate the 'quickstart' found on the main JS sdk. I've seen some success, but it is clear that no matter what I do the DefaultAccount does not function as anticipated. See https://github.com/starling-foundries/gozilliqa-example for the code that triggers this error.

**Comment by csajedi** [comment] 2019-10-15 16:22
There is a workaround using "signWith" but it is not possible to do within contract deployment.

**Comment by renlulu** [comment] 2019-10-15 22:34
Thanks man ! But as we discuss on discord, this may not caused by `sdk` side, so close it now : )

**Closed** 2019-10-15 22:34 UTC
